name: E2E test
description: Runs the E2E test

inputs:
  working-directory:
    description: 'The working directory where the tests are located'
    required: false
    default: './e2e'
  # Variables
  M365_PAGE_URL:
    description: 'URL of the environment'
    required: true
  M365_WEBHOOK_URL:
    description: 'URL of the webhook to send the results to'
    required: true
  # Secrets
  M365_USERNAME:
    description: 'Username for the environment'
    required: true
  M365_PASSWORD:
    description: 'Password for the environment'
    required: true
  M365_OTP_SECRET:
    description: 'OTP secret for the M365 environment'
    required: true
  
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      working-directory: ${{ inputs.working-directory }}
      with:
        node-version: 20
        cache: npm

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm ci

    - name: Store Playwright's Version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        PLAYWRIGHT_VERSION=$(npm ls @playwright/test --depth=0 | grep @playwright | sed 's/.*@//')
        echo "Playwright's Version: $PLAYWRIGHT_VERSION"
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

    - name: Cache Playwright Browsers for Playwright's Version
      id: cache-playwright-browsers
      uses: actions/cache@v4
      working-directory: ${{ inputs.working-directory }}
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

    - name: Install Playwright Browsers
      shell: bash
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps chromium

    - name: Run Playwright tests
      run: npx playwright test
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        M365_PAGE_URL: ${{ inputs.M365_PAGE_URL }}
        M365_USERNAME: ${{ inputs.M365_USERNAME }}
        M365_PASSWORD: ${{ inputs.M365_PASSWORD }}
        M365_OTP_SECRET: ${{ inputs.M365_OTP_SECRET }}
        M365_WEBHOOK_URL: ${{ inputs.M365_WEBHOOK_URL }}

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      working-directory: ${{ inputs.working-directory }}
      with:
        name: snapshots
        path: tests/**/*-snapshots/
        retention-days: 30

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      working-directory: ${{ inputs.working-directory }}
      with:
        name: report
        path: playwright-report/
        retention-days: 30