name: E2E Testing

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  testing:
    name: Start E2E Testing
    timeout-minutes: 60
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./e2e

    steps:
      - uses: actions/checkout@v4

      - name: Run the E2E test
        uses: ./.github/actions/playwright
        with:
          # Variables
          M365_PAGE_URL: ${{ vars.M365_PAGE_URL }}
          M365_WEBHOOK_URL: ${{ vars.M365_WEBHOOK_URL }}
          # Secrets
          M365_USERNAME: ${{ secrets.M365_USERNAME }}
          M365_PASSWORD: ${{ secrets.M365_PASSWORD }}
          M365_OTP_SECRET: ${{ secrets.M365_OTP_SECRET }}
