name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  testing:
    name: e2e testing with auth session
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Create the auth file based on the contents from `secrets.M365_AUTH_SESSION`
      - uses: actions/github-script@v7
        with:
          script: |
            const { writeFileSync } = require('fs');
            const authSession = process.env.M365_AUTH_SESSION;
            writeFileSync('./e2e/auth.json', authSession, 'utf8');
        env:
          M365_AUTH_SESSION: ${{ secrets.M365_AUTH_SESSION }}

      # - name: Create the auth file
      #   run: node ./scripts/create.auth.mjs
      #   working-directory: ./e2e
      #   env:
      #     M365_AUTH_SESSION: ${{ secrets.M365_AUTH_SESSION }}

      - name: Run the E2E test
        uses: ./.github/actions/playwright
        with:
          M365_PAGE_URL: ${{ vars.M365_PAGE_URL }}
          M365_WEBHOOK_URL: ${{ vars.M365_WEBHOOK_URL }}
          M365_USERNAME: ${{ secrets.M365_USERNAME }}
          M365_PASSWORD: ${{ secrets.M365_PASSWORD }}
          M365_OTP_SECRET: ${{ secrets.M365_OTP_SECRET }}
          AZURE_STORAGE_URL: ${{ vars.AZURE_STORAGE_URL }}
          AZURE_STORAGE_SAS: ${{ secrets.AZURE_STORAGE_SAS }}
          environment: production

      - name: Update the auth session
        if: ${{ !cancelled() }}
        working-directory: ./e2e
        run: |
          echo "Updating the auth session"
          updatedAuthSession=$(cat ./auth.json)
          gh secret set 'M365_AUTH_SESSION' --body "$updatedAuthSession" --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SECRETS_TOKEN }}