name: Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build the SPFx solution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build SPPKG
        uses: ./.github/actions/build
        with:
          ARTIFACT_NAME: "pointfire-express-app"
          PACKAGE_FOLDER: "./packages/pointfire-express-app"

  deploy_test:
    name: Deploy SPFx to test environment
    runs-on: ubuntu-latest
    environment: test
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Deploy SPFx
        uses: ./.github/actions/deploy
        with:
          ARTIFACT_NAME: "pointfire-express-app"
          PACKAGE_NAME: "pointfire-express-app.sppkg"
          ENTRA_TENANT_ID: ${{ vars.ENTRA_TENANT_ID }}
          ENTRA_APP_ID: ${{ vars.ENTRA_APP_ID }}
          APP_CATALOG_URL: ${{ vars.APP_CATALOG_URL }}
          CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
